config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :prompts do
    resources :comments, only: [:create, :destroy]
  end
  resources :resource_links do
    resources :comments, only: [:create, :destroy]
  end
  resources :resource_categories
  root 'prompts#index'
  get 'about', to: 'pages#about'

  # API
  namespace :api do
    namespace :v1 do
      resources :prompts, only: [:index, :show]
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prompt
  belongs_to :commentable, polymorphic: true
end

app/models/prompt.rb
class Prompt < ApplicationRecord
    has_many :comments, dependent: :destroy, as: :commentable
end

app/models/resource_category.rb
class ResourceCategory < ApplicationRecord
end

app/models/resource_link.rb
class ResourceLink < ApplicationRecord
  belongs_to :resource_category
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
end

app/controllers/api/v1/prompts_controller.rb
module Api
    module V1
      class PromptsController < ApplicationController
        protect_from_forgery with: :null_session
  
        def index
          prompts = Prompt.all
          render json: prompts, status: :ok
        end
  
        def show
          prompt = Prompt.find(params[:id])
          render json: prompt, status: :ok
        rescue ActiveRecord::RecordNotFound
          render json: { error: "Prompt not found" }, status: :not_found
        end
      end
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_commentable
    
    def create
        @comment = @commentable.comments.create(comment_params.merge(user: current_user))
        redirect_to @commentable
      end

      def destroy
        @comment = Comment.find(params[:id])
        @commentable = @comment.commentable
    
        if @comment.destroy
          redirect_to @commentable, notice: "Comment was successfully deleted."
        else
          redirect_to @commentable, alert: "Error deleting comment."
        end
      end
    
      private
    
      def set_commentable
        resource, id = request.path.split('/')[1, 2]
        @commentable = resource.singularize.classify.constantize.find(id)
      end
    
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
  end
  

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_action :set_prompt, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  # GET /prompts or /prompts.json
  def index
    @prompts = Prompt.all
  end

  # GET /prompts/1 or /prompts/1.json
  def show
  end

  # GET /prompts/new
  def new
    @prompt = Prompt.new
  end

  # GET /prompts/1/edit
  def edit
  end

  # POST /prompts or /prompts.json
  def create
    @prompt = Prompt.new(prompt_params)

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to prompt_url(@prompt), notice: "Prompt was successfully created." }
        format.json { render :show, status: :created, location: @prompt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prompts/1 or /prompts/1.json
  def update
    respond_to do |format|
      if @prompt.update(prompt_params)
        format.html { redirect_to prompt_url(@prompt), notice: "Prompt was successfully updated." }
        format.json { render :show, status: :ok, location: @prompt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1 or /prompts/1.json
  def destroy
    @prompt.destroy

    respond_to do |format|
      format.html { redirect_to prompts_url, notice: "Prompt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      @prompt = Prompt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prompt_params
      params.require(:prompt).permit(:title, :prompt_text, :description)
    end
end

app/controllers/resource_categories_controller.rb
class ResourceCategoriesController < ApplicationController
    def index
      @resource_categories = ResourceCategory.all
    end
  
    def show
      @resource_category = ResourceCategory.find(params[:id])
    end
  
    def new
      @resource_category = ResourceCategory.new
    end
  
    def create
      @resource_category = ResourceCategory.new(resource_category_params)
      if @resource_category.save
        redirect_to @resource_category, notice: 'Resource category was successfully created.'
      else
        render :new
      end
    end
  
    def edit
      @resource_category = ResourceCategory.find(params[:id])
    end
  
    def update
      @resource_category = ResourceCategory.find(params[:id])
      if @resource_category.update(resource_category_params)
        redirect_to @resource_category, notice: 'Resource category was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @resource_category = ResourceCategory.find(params[:id])
      @resource_category.destroy
      redirect_to resource_categories_url, notice: 'Resource category was successfully destroyed.'
    end
  
    private
  
    def resource_category_params
      params.require(:resource_category).permit(:name)
    end
  end
  

app/controllers/resource_links_controller.rb
class ResourceLinksController < ApplicationController
    before_action :set_resource_link, only: %i[ show edit update destroy ]

    def index
        @resource_links = ResourceLink.includes(:resource_category).all
    end

    def show
    end

    def new
        @resource_link = ResourceLink.new
    end

    def edit
    end

    def create
        @resource_link = ResourceLink.new(resource_link_params)

        respond_to do |format|
            if @resource_link.save
                format.html { redirect_to @resource_link, notice: "Resource link was successfully created." }
                format.json { render :show, status: :created, location: @resource_link }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @resource_link.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        if @resource_link.update(resource_link_params)
            redirect_to @resource_link, notice: "Resource link was successfully updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @resource_link.destroy
        redirect_to resource_links_url, notice: "Resource link was successfully destroyed."
    end

    private
    def set_resource_link
        @resource_link = ResourceLink.find(params[:id])
    end

    def resource_link_params
        params.require(:resource_link).permit(:title, :url, :description, :image_url, :resource_category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/resource_categories_helper.rb
module ResourceCategoriesHelper
end

app/helpers/resource_links_helper.rb
module ResourceLinksHelper
end

app/views/comments/_comments.html.erb
<div class="comments">
  <h4>Comments (<%= commentable.comments.count %>)</h4>
  <% commentable.comments.each do |comment| %>
    <div class="comment">
      <p><strong><%= comment.user.email %></strong> commented:</p>
      <p><%= simple_format(comment.content) %></p>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
   <%= form_for([commentable, Comment.new]) do |f| %>
    <div class="form-group">
      <%= f.label :content, "Add a comment" %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Promptitude</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Resources', resource_links_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-target="#dropdown-menu">
  <%= current_user.email %>
</a>
<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink" id="dropdown-menu">
  <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
  <li><%= form_tag destroy_user_session_path, method: :delete, class: "signout-form" do %>
  <%= submit_tag "Sign out", class: "dropdown-item" %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<% end %></li>
</ul>
          </li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %></li>
          <li class="nav-item"> <%= link_to "Register", new_user_registration_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Promptitude</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,500,600,700&display=swap" rel="stylesheet">
    <%# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.6.0/css/bootstrap.min.css" integrity="sha384-pzjw8f+ua7Kw1TIq0v8FqFjcJ6pajs/rfdfs3SO+kD4Ck5BdPtF+to8xM6v1XmRo7M" crossorigin="anonymous"> %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Popper.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.1/js/bootstrap.min.js"></script>
  </head>

  <body>
  <%= render 'layouts/navbar' %>


    <%= yield %>
   

  </body>
</html>

app/views/pages/about.html.erb
<div class="container mt-4 mb-4">
<h1>About Promptitude</h1>
    <p>Promptitude is a database of useful prompts for ChaptGPT created by Tom Leger, a seasoned software developer with a passion for building innovative solutions that make people's lives easier. </p>
    <p>If you're interested in learning more about Tom Leger and his work, you can visit his portfolio at <a href="https://tomleger.dev" target="_blank">tomleger.dev</a> or check out his Github account at <a href="https://github.com/legertom" target="_blank">github.com/legertom</a>.</p>
    <p>Promptitude is an open-source project hosted on <a href="https://github.com/legertom/prompter" target="_blank">Github</a>, and we welcome contributions from anyone who is interested in improving our database of prompts.</p>
    <h2>Promptitude API</h2>
    To access our free API, see instructions at <a href="https://github.com/legertom/prompter">https://github.com/legertom/prompter</a>.
    <h2>Technology</h2>
    <p>We are proud to be running on Rails 7, powered by a PostgreSQL database, and hosted on <a href="https://render.com/" target="_blank">Render</a>, ensuring high performance and reliability for all users.</p>
    <p>At Promptitude, we are committed to providing a high-quality resource for ChaptGPT users, and we are constantly working to improve and expand our database of prompts. So come on in and explore, and feel free to contribute to the open-source project.</p>
</div>

app/views/prompts/_form.html.erb
<%= form_with(model: prompt, local: true, html: { class: 'prompt-form' }) do |form| %>
  <% if prompt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prompt.errors.count, "error") %> prohibited this prompt from being saved:</h2>

      <ul>
        <% prompt.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :prompt_text, class: 'form-label' %>
    <%= form.text_area :prompt_text, class: 'form-control', rows: 10 %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/prompts/_prompt.html.erb
<div id="<%= dom_id prompt %>">
  <p>
    <strong>Title:</strong>
    <%= prompt.title %>
  </p>

  <p>
    <strong>Prompt text:</strong>
    <%= prompt.prompt_text %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= prompt.description %>
  </p>

</div>

app/views/prompts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h1>Editing Prompt</h1>

      <%= render 'form', prompt: @prompt %>

      <%= link_to 'Show', @prompt %> |
      <%= link_to 'Back', prompts_path %>
    </div>
  </div>
</div>

app/views/prompts/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>
  <h1 class="my-4">Prompts</h1>

                <% if user_signed_in? %>

<%= link_to 'New Prompt', new_prompt_path, class: 'btn btn-primary' %>

<% end %>

  <div class="row">
  <% @prompts.each do |prompt| %>
    <div class="row"> 
      <div class="col-md-8 mx-auto"> <!-- Update this line -->
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= prompt.title %></h5>
            <p class="card-text"><%= prompt.description %></p>
            <p class="card-text"><%= simple_format(prompt.prompt_text) %></p>
            <%= link_to 'Show', prompt, class: 'btn btn-primary' %>
            <% if user_signed_in? %>
            <%= link_to 'Edit', edit_prompt_path(prompt), class: 'btn btn-secondary' %>
            <%= link_to 'Delete', prompt, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div> 
  <% end %>
  
  </div>

  <div class="d-flex justify-content-center">
    <%= link_to 'New Prompt', new_prompt_path, class: 'btn btn-primary mt-3' %>
  </div>
</div>

app/views/prompts/new.html.erb
<div class="container mt-4 mb-4">
<h1>New prompt</h1>

<%= render "form", prompt: @prompt %>

<br>

<div>
  <%= link_to "Back to prompts", prompts_path %>
</div>

</div>

app/views/prompts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
    <p style="color: green"><%= notice %></p>
      <div class="mt-4">
        <h1><%= @prompt.title %></h1>
        <p><span style="color: gray; font-style: italic;"><%= @prompt.description %></span></p>
        <p><%= simple_format(@prompt.prompt_text) %></p>
      </div>

      <%= link_to 'Edit', edit_prompt_path(@prompt), class: 'btn btn-secondary' %> |
      <%= link_to 'Back', prompts_path, class: 'btn btn-link' %>
      <%= render 'comments/form', commentable: @prompt %>
      <%= render 'comments/comments', commentable: @prompt %>

    </div>
    
  </div>
</div>

app/views/resource_categories/_form.html.erb
<%= form_with(model: resource_category, local: true) do |form| %>
    <% if resource_category.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(resource_category.errors.count, "error") %> prohibited this resource category from being saved:</h4>
        <ul>
          <% resource_category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
  

app/views/resource_categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="display-4">Edit Resource Category</h1>
      <%= render 'form', resource_category: @resource_category %>
      <%= link_to 'Cancel', resource_category_path(@resource_category), class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/resource_categories/index.html.erb
<div class="container">
<h1 class="my-4">
Resource Categories</h1>
<div class="mb-3">
<%= link_to 'New Resource Category', new_resource_category_path, class: 'btn btn-primary' %>

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @resource_categories.each do |resource_category| %>
        <tr>
          <td><%= resource_category.id %></td>
          <td><%= resource_category.name %></td>
          <td>
            <%= link_to 'Show', resource_category, class: 'btn btn-info btn-sm' %>
            <%= link_to 'Edit', edit_resource_category_path(resource_category), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Delete', resource_category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/resource_categories/new.html.erb
<div class="container">
  <h1 class="my-4">New Resource Category</h1>

  <%= render 'form', resource_category: @resource_category %>

  <div class="mb-3">
    <%= link_to 'Back to Resource Categories', resource_categories_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/resource_categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="display-4"><%= @resource_category.name %></h1>
      <p class="lead"><%= @resource_category.description %></p>
      <hr>
      <%= link_to 'Edit', edit_resource_category_path(@resource_category), class: 'btn btn-primary' %>
      <%= link_to 'Back', resource_categories_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/resource_links/_form.html.erb
<%= form_with(model: resource_link, local: true) do |form| %>
    <% if resource_link.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(resource_link.errors.count, "error") %> prohibited this resource_link from being saved:</h2>
        <ul>
          <% resource_link.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :url %>
      <%= form.text_field :url, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :image_url %>
      <%= form.text_field :image_url, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :resource_category_id, "Category" %>
      <%= form.collection_select :resource_category_id, ResourceCategory.all, :id, :name, {}, {class: 'form-control'} %>
    </div>
  
    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
  

app/views/resource_links/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="display-4">Edit Resource Link</h1>
      <%= render 'form', resource_link: @resource_link %>
      <%= link_to 'Cancel', resource_link_path(@resource_link), class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/resource_links/index.html.erb
<div class="container">

<h1 class="mb-4">Resource Links</h1>
<% if current_user%>
<%= link_to 'New Resource Link', new_resource_link_path, class: 'btn btn-primary' %>
<%= link_to 'New Resource Category', new_resource_category_path, class: 'btn btn-sm btn-outline-primary'  %>
<%= link_to 'All Resource Categories', resource_categories_path, class: 'btn btn-sm btn-outline-primary' %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Description</th>
      <th>Image</th>
      <th>Category</th>
      <% if current_user %>
      <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @resource_links.each do |resource_link| %>
      <tr>
        <td><%= resource_link.title %></td>
        <td><%= link_to resource_link.url, resource_link.url, target: "_blank" %></td>
        <td><%= resource_link.description %></td>
        <td><%= image_tag(resource_link.image_url, class: "img-thumbnail", style: "width: 100px;") if resource_link.image_url.present? %></td>
        <td><%= resource_link.resource_category.name %></td>
        <% if current_user%>
        <td>
          <%= link_to 'Edit', edit_resource_link_path(resource_link), class: 'btn btn-sm btn-warning' %> |
          <%= link_to 'Delete', resource_link, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>



</div>

app/views/resource_links/new.html.erb
<div class="container">
<h1 class="mb-4">New Resource Link</h1>

<%= render 'form', resource_link: @resource_link %>

<%= link_to 'Back to Resource Links', resource_links_path, class: 'btn btn-secondary' %>

</div>

app/views/resource_links/show.html.erb
<div class="container">
  <h1 class="mb-4"><%= @resource_link.title %></h1>
  
  <div class="row">
    <div class="col-md-6">
      <p><strong>Link:</strong> <%= link_to @resource_link.url, @resource_link.url, target: '_blank', rel: 'noopener' %></p>
      <p><strong>Description:</strong> <%= @resource_link.description %></p>
      <p><strong>Category:</strong> <%= @resource_link.resource_category.name %></p>
    </div>
    <div class="col-md-6">
      <%= image_tag @resource_link.image_url, alt: @resource_link.title, class: 'img-fluid' %>
    </div>
  </div>

  <div class="mt-4">
    <%= link_to 'Edit', edit_resource_link_path(@resource_link), class: 'btn btn-primary mr-2' %>
    <%= link_to 'Back to Resource Links', resource_links_path, class: 'btn btn-secondary mr-2' %>
    <%= button_to 'Delete', @resource_link, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </div>
  <%= render 'comments/form', commentable: @resource_link %>
      <%= render 'comments/comments', commentable: @resource_link %>
</div>